### ISSUE TITLE
Does not clear old videos

### ISSUE THREAD

**Issue by Deiyvien** [DuBistKomisch/nou2ube#1]
I am seeing videos from up to 2 months ago, which i think is also causing it to slow to a crawl when i try to ignore a video.
it can take up to 30 seconds to actually remove the listing for the video.

Would be nice to be able to clear all of the videos.

**Comment by Deiyvien** [comment]
![screen shot 2017-05-22 at 12 37 43 am](https://cloud.githubusercontent.com/assets/26861388/26284856/02eb2cea-3e88-11e7-9003-0f8587c722d8.png)

**Comment by DuBistKomisch** [comment]
Fixed in https://github.com/DuBistKomisch/nou2ube/commit/e55f9b6c805c1cf23a6d0c629c6e8fe329fce23f.
